### ISSUE TITLE
Unable to delete HelmRelease

### ISSUE THREAD

**Issue by CapKenR** [weaveworks/vscode-gitops-tools#369]
### Expected behaviour

I right-click on a HelmRelease under Workloads in the extension. I expect the selected HelmRelease to be deleted from my Kubernetes cluster.

### Actual behaviour

Instead, I get a message that says "Delete HelmRelease not supported on Azure cluster."

### Steps to reproduce

I used Tanzu Kubernetes Grid to install a Kubernetes (v1.22.9+vmare.1) cluster in Azure. I then bootstrapped Flux in the cluster and added a couple of simple HelmRepository and HelmRelease resources (Traefik and Sealed-Secrets in this case) via kubectl. Finally, tried to delete the HelmRelease resources via the extension.

### Versions

kubectl client v1.22.9+vmware.1
kubectl server v1.22.9+vmware.1
Flux: v0.31.1
Git: 2.25.1
Azure: 2.37.0
Azure extension "k8s-configuration": not installed
Azure extension "k8s-extension": not installed
VSCode: 1.71.0-insider
Extension: 0.20.1659723293
OS: Linux x64 5.15.57.1-microsoft-standard-WSL2

Note: I'm not sure what the Azure extensions are or why they'd be needed. I don't need them from a command line.

**Comment by kingdonb** [comment]
Thanks for the report. We plan to address several outstanding Azure issues in our next sprint! This one is on our radar now.

**Comment by kingdonb** [comment]
If you are not using the Azure Microsoft.Flux extension then you should be able to set the cluster provider to Generic in the right click menu for the cluster. This should be auto-detected but unfortunately there is a bug, or we haven't considered the cases where you are on Azure but you aren't using Azure extensions, just Azure compute nodes with some other Kubernetes distribution than AKS, and a generic Flux.

@juozasg

**Comment by CapKenR** [comment]
When I changed the cluster provider to generic I was able to delete the HelmRelease I wasn't able to delete before.

**Comment by kingdonb** [comment]
You're not using Azure Arc or anything – this is a generic cluster with no Microsoft extensions at all – got it 👍 

There should be three choices, this one Generic and also:

* AKS - managedClusters,
* Azure Arc - connectedClusters

We are aware of some autodetection logic issues and will take this case into account when we do a release to cover this issue. When you set the cluster to Generic, does it retain this setting? We'll check on this as well...

Here is the logic that selects the `AKS` cluster provider, does it look like this makes sense?
https://github.com/weaveworks/vscode-gitops-tools/blob/6c1d07c6ae398ed6fc35e689b4e727a9dd5e9f5c/src/kubernetes/kubernetesTools.ts#L491-L492

I think you can check on the node details and find out if this `azure://` is the prefix of your nodes providerID in `kubectl get nodes -oyaml` like this check?

If so, then we need to find a better way to detect managed AKS clusters.

**Comment by CapKenR** [comment]
The logic in the code isn't sufficient to determine if it's AKS or not. The provider ID for my nodes matches.
```
  providerID: azure:///subscriptions/a0b0c0d0-e1f1-a2b2-c3d3-abcdef123456/resourceGroups/kdr-tkg/providers/Microsoft.Compute/virtualMachines/tkg-workload-azure-md-0-2qm74
```
The only thing I can see in the node manifest that might tell you it's a TKG cluster and not an AKS cluster is `kubeProxyVersion` and `kubeletVersion`. But I don't know if that's sufficient and I don't (right now) have an AKS cluster to compare it with.
```
    kubeProxyVersion: v1.22.9+vmware.1
    kubeletVersion: v1.22.9+vmware.1
```

**Comment by CapKenR** [comment]
On your other question, at least so far it has kept its Generic designation.

**Comment by CapKenR** [comment]
@kingdonb, in looking at the nodes in an AKS cluster, you might be better off checking the series of `kubernetes.azure.com/*` labels that are applied to the AKS nodes. I checked 3 AKS clusters and they all had them. Here's an example.

```
metadata:
  labels:
    kubernetes.azure.com/agentpool: agentpool
    kubernetes.azure.com/cluster: MC_rg-test-eastus-dev_aks-test-eastus-dev_eastus
    kubernetes.azure.com/kubelet-identity-client-id: 1a2b3c4d-a1b2-c3d4-5e6f-123abc456def
    kubernetes.azure.com/mode: system
    kubernetes.azure.com/node-image-version: AKSUbuntu-1804gen2containerd-2022.06.13
    kubernetes.azure.com/os-sku: Ubuntu
    kubernetes.azure.com/role: agent
    kubernetes.azure.com/storageprofile: managed
    kubernetes.azure.com/storagetier: Premium_LRS
```
