### ISSUE TITLE
Failed to get contexts

### ISSUE THREAD

**Issue by CapKenR** [weaveworks/vscode-gitops-tools#393]
### Expected behaviour

When I open the GitOps Tools extension I expect it to use the current context from my kubeconfig. It's always worked that way in the past.

### Actual behaviour

Instead, I get a message saying "Failed to get contexts: Config fetched, but contexts not found."

### Steps to reproduce

Open `code` from a WSL command line. Select the GitOps Toolkit extension.

### Versions

kubectl client v1.25.0
kubectl server v1.22.9+vmware.1
Flux: v0.32.0
Git: 2.25.1
Azure: 2.40.0
Azure extension "k8s-configuration": not installed
Azure extension "k8s-extension": not installed
VSCode: 1.72.0
Extension: 0.22.0
OS: Linux x64 5.15.57.1-microsoft-standard-WSL2

**Comment by kingdonb** [comment]
Thanks for the report! I'm sorry we haven't got back to you before now! We have been embroiled in some KubeCon related things and missed you.

Have you been able to resolve this? We expect the `KUBECONFIG` environment variable to be respected, unless you have leveraged the `Set KubeConfig` option here, which can change the setting for both the GitOps Tools extension and the Kubernetes Tools extension together. (We use their contribution point, so it is the same KUBECONFIG on the backend.)

I think this feature should be present in the version that you have installed. Please let us know if you gave up, or if this might have been resolved?

**Comment by CapKenR** [comment]
It's still broken. I do notice now another error message, "Failed to get contexts: Config fetched, but contexts not found." I don't have the KUBECONFIG environment variable set. A `kubectl config get-contexts` shows 5 contexts.

**Comment by CapKenR** [comment]
I deleted the 2 contexts that didn't work but still get the same error.

**Comment by CapKenR** [comment]
There is an additional error message now. (See below.) I'm not sure why it would be trying to connect to localhost:8080 as it's not referenced anywhere in ~/.kube/config.

"Failed to get namespaces W1118 10:18:44.957472 6790 loader.go:221] Config not found: [object Object] The connection to the server localhost:8080 was refused - did you specify the right host or port?"

**Comment by kingdonb** [comment]
Can you provide a screenshot so we can see some context of the error and how it's presented?

Thanks for following up 👍 another question, if you do "Command-Shift P" or however you get to the command palate on your OS, and check the config through this option:
<img width="603" alt="Screenshot 2022-11-18 at 12 21 30 PM" src="https://user-images.githubusercontent.com/3286998/202764531-cfd3d52f-2087-4875-b51e-867ff8d5a303.png">

do you find a config section that matches this:

<img width="885" alt="Screenshot 2022-11-18 at 12 23 14 PM" src="https://user-images.githubusercontent.com/3286998/202764729-4ddf1fab-516b-45bb-bdf4-bad7816b15eb.png">

I suspect that the environment variable is being lost, or the config setting is not being used properly, perhaps it has been overridden somewhere.

What other information might help us to debug this: a sanitized version of your kubeconfig and any env variables that might be kubectl-related from your env (again, sanitized)

We definitely are going to have some WSL linux users, and it's a fact that one of us on the developer team is using WSL as well, (maybe @juozasg can help us shed some light) on whether he has had a similar experience?

If so we can add an FAQ how to work around it. Thank you for the added detail @CapKenR !

When there is no kubeconfig, the default behavior of kubectl is to check `localhost:8080` for an unsecured endpoint, like used to be possible in Kubernetes versions ~1.4 or thereabouts, back before RBAC was enabled by default, and insecure localhost access with no auth required was considered OK... (and that's why I suspect the KUBECONFIG setting simply is not being honored, it seems that either it is being lost on the way into VSCode or lost on the way out to the `kubectl` CLI.)

I don't remember exactly how many versions back that is, and it's probably not important either, but I suppose there is probably some non-vestigial explanation for that behavior to remain in the client, now that insecure configs are less commonplace/generally prevented from a policy perspective in the standard kubeadm distro. Anyway, that's how you get `localhost:8080` connections when there is no such cluster endpoint in the kubeconfig file, it likely means that the kubeconfig file isn't connected at all.

**Comment by CapKenR** [comment]
First, it’s not just a WSL problem. If I open VS Code from PowerShell and the Windows desktop, I get the same behavior. I made a short video of starting VS Code from WSL then going to the GitOps extension. You can find it at https://clipchamp.com/watch/gDzBy58oP1l.

Second, my settings.json, regardless of where I open VS Code from, is the same and doesn’t have a `vs-kubernetes.knownKubeconfigs`. It only has a `vs-kubernetes.kubeconfig`.

```json
    "vs-kubernetes": {
        "vs-kubernetes.kubeconfig": {
            "collapsibleState": 2,
            "label": "docker-desktop",
            "children": [],
            "clusterProvider": "Generic",
            "clusterProviderManuallyOverridden": false,
            "isCurrent": true,
            "cluster": {
                "name": "docker-desktop",
                "cluster": {
                    "server": "https://kubernetes.docker.internal:6443",
                    "certificate-authority-data": "DATA+OMITTED"
                }
            },
            "clusterContext": {
                "name": "docker-desktop",
                "context": {
                    "cluster": "docker-desktop",
                    "user": "docker-desktop",
                    "clusterInfo": {
                        "name": "docker-desktop",
                        "cluster": {
                            "server": "https://kubernetes.docker.internal:6443",
                            "certificate-authority-data": "DATA+OMITTED"
                        }
                    }
                }
            },
            "clusterName": "docker-desktop",
            "contextName": "docker-desktop",
            "description": "https://kubernetes.docker.internal:6443",
            "iconPath": {
                "light": {
                    "$mid": 1,
                    "path": "/c:/Users/KenRider/.vscode/extensions/weaveworks.vscode-gitops-tools-0.22.3/resources/icons/light/cloud.svg",
                    "scheme": "file"
                },
                "dark": {
                    "$mid": 1,
                    "path": "/c:/Users/KenRider/.vscode/extensions/weaveworks.vscode-gitops-tools-0.22.3/resources/icons/dark/cloud.svg",
                    "scheme": "file"
                }
            },
            "isGitOpsEnabled": false
        }
    },
```

My WSL kubeconfig (/home/ken/.kube/config):
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://kubernetes.docker.internal:6443
  name: cluster-b796g6fbkm
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://tkg-mgmt-azure-20220609080551-xxxxxxxx.westus2.cloudapp.azure.com:6443
  name: tkg-mgmt-azure-20220609080551
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://tkg-workload-azure-xxxxxxx.westus2.cloudapp.azure.com:6443
  name: tkg-workload-azure
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: tkg-mgmt-azure-20220609080551
    user: tkg-mgmt-azure-20220609080551-admin
  name: tkg-mgmt-azure-20220609080551-admin@tkg-mgmt-azure-20220609080551
- context:
    cluster: tkg-workload-azure
    namespace: default
    user: tkg-workload-azure-admin
  name: tkg-workload-azure-admin@tkg-workload-azure
current-context: tkg-mgmt-azure-20220609080551-admin@tkg-mgmt-azure-20220609080551
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
- name: tkg-mgmt-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
- name: tkg-mgmt-azure-20220609080551-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
- name: tkg-workload-azure-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
- name: user-b796g6fbkm
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

My Windows kubeconfig (C:\Users\KenRider\.kube\config):
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

In regards to the localhost:8080 question, it must not be using my default kubeconfig or the kubeconfig referenced in settings.json as both have valid contexts.
